### ISSUE TITLE
Ubuntu 16.04: Permission denied?

### ISSUE THREAD

**Issue by mabkenar** [ivandokov/phockup#10]
I installed PhockUp in Ubuntu 16.04 using `sudo snap install phockup`. Then I ran it like this:

`$ phockup ownCloud/InstantUpload/ InstantUploadSorted/`
**`/snap/phockup/25/command-phockup.wrapper: 6: exec: /snap/phockup/25/phockup.sh: Permission denied`**

Is it intentional? Do I have to run it with root permission? (I haven't tested if it works with root permission for obvious reasons.) I find it a bit surprising if arranging and copying files in my home directory requires root access. Could you please give a hint, or is this a bug?

**Comment by mabkenar** [comment]
By the way, thank you for this nice and handy tool. I read about it in OMG! Ubuntu! and immediately tried to use it, as I think it can be really helpful in organizing my photos and other media files.

**Comment by ivandokov** [comment]
It shouldn't ask you for permissions. Can you please download the latest snap release and try again.
Also can you please paste the full path to `ownCloud` folder. Is it located in your home directory?

**Comment by mabkenar** [comment]
I didn't change anything. But it is working now. Thanks.
