### ISSUE TITLE
Option to add suffix to duplicated files

### ISSUE THREAD

**Issue by seanmikhaels** [ivandokov/phockup#112]
Instead of reporting files as "duplicate", add switch option to place a suffix. This would be useful for burst photos, or edits that have the exact same exif time stamp. 

Example would be 

photo-extract/photos/photo1.jpg => skipped, duplicated file photo-sorted/2018/Mar/20180314-23342125.jpg
photo-extract/photos/photo2.jpg => skipped, duplicated file photo-sorted/2018/Mar/20180314-23342125.jpg

option would add suffix _1, _2, etc for each duplicate found

photo-extract/photos/photo1.jpg => skipped, duplicated file photo-sorted/2018/Mar/20180314-23342125_1.jpg
photo-extract/photos/photo2.jpg => skipped, duplicated file photo-sorted/2018/Mar/20180314-23342125_2.jpg

**Comment by ivandokov** [comment]
Duplicates are marked as duplicates if they have the same checksum. Edits are counted as unique files. The exif date is not used. If the file is marked as duplicated it is really a duplicate, otherwise it is with a suffix.
