### ISSUE TITLE
 phockup -v shows v1.6.3

### ISSUE THREAD

**Issue by roykrikke** [ivandokov/phockup#119]
Hello Ivan,

There is a small issue when using snap to install phockup. The current install shows v1.6.3 of phockup . But we are still on 1.6.1. How can I help to fix this issue. I have no experience with snap yet.

Thanks
Roy

**Comment by ivandokov** [comment]
Looks like I tagged two new versions but forgot to update the version in the code. 
Unfortunatelly new version were required even though no new code was introduced but only Github Actions changes were made. Thank you for the report. I'll fix it right now.
