### ISSUE TITLE
Folder-related errors

### ISSUE THREAD

**Issue by Skeltzer** [ivandokov/phockup#12]
Hi Ivan,

I get some strange errors related to the input and output folders:

`$ phockup . /outputdir`
`Input directory "." does not exist`

Of course it exists, "." is always there. Perhaps the problem is that the current directory name has a space in it? Trying again with the full pathname to the current directory:

`$ phockup ~/Dropbox/Camera\ Uploads /outputdir`
`Input directory "/home/jos/Dropbox/Camera Uploads" does not exist`

Another attempt:
```
$ phockup . /mnt/tower/Media/Foto\'s/
Output directory "/mnt/tower/Media/Foto's/" does not exist, creating now
Traceback (most recent call last):
  File "/snap/phockup/27/lib/phockup/phockup.py", line 263, in <module>
    main(sys.argv[1:])
  File "/snap/phockup/27/lib/phockup/phockup.py", line 28, in main
    os.makedirs(outputdir)
  File "/snap/phockup/27/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/snap/phockup/27/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/snap/phockup/27/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/mnt/tower'
```
The output directory is already there, it shouldn't have to be created. Also `/mnt/tower` is not a read-only file system; it is writable, as I can confirm right after this command.

What can I do?

Jos

**Comment by ivandokov** [comment]
Thanks for the report. 
It seems I've forgot to handle the case when you can specify `.` for path.

The space in the path is an interesting case. I will have to take a closer look and I will post and update.

**Comment by ivandokov** [comment]
Can you please check the latest version and tell me if it is having the same issues.

The `/mnt` directory is not writable by snap applications. You should try on files which are located somewhere in your home directory. The Dropbox one should not have any problems.

**Comment by Skeltzer** [comment]
Yes, it works now.
Except on the /mnt folder, which is pretty useless, as all my photos reside on a network drive, and I'm sure I'm not the only one. Not your fault though.

Thanks.

**Comment by ivandokov** [comment]
Can you please install the latest edge release and test again. 
`sudo snap refresh phockup --edge`
It should be release 50.

**Comment by Skeltzer** [comment]
Yes, it is release 50. It works, just as it did 35 minutes ago (i.e. to a local directory, not to /mnt).

**Comment by ivandokov** [comment]
Thanks.
