### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by inverse** [ivandokov/phockup#122]
Publishing this on pypi will enable installation through standard tooling like pip as well as nicer packaging tools such as [pipx](https://pypa.github.io/pipx/).

I recommend using a tool such as [poetry](https://python-poetry.org/) to ease development as well as packaging up the application.

**Comment by ivandokov** [comment]
Thank you for the suggestion. This software is not a Python library that has to live in Python packaging repositories. It just happens to be written in Python and that's completely by accident and my curiosity to try to do something meaningful with the language other than a simple TODO app that will end up in the bin. 

I'd like the software to be packaged in common packages such as snap for Linux, Homebrew for mac and I'm completely open for some automated Windows packaging but that will require GUI so I think a simple one that we tried to create before is a good option. Also I have exactly zero experience developing and shipping Windows apps so PRs are more than welcome in this area!

With that being said I am open for pushing the software to pypi if someone can automate this with Github Actions as I want all deployment actions to be done there.
