### ISSUE TITLE
 phockup 1.7 snap fails import tqdm

### ISSUE THREAD

**Issue by darkanthey** [ivandokov/phockup#129]
After snap update to 1.7 version
phockup failed with ModuleNotFoundError: No module named 'tqdm'

**Comment by albertmichaelj** [comment]
This error also appears when trying to use phockup via docker.

**Comment by inverse** [comment]
`tqdm` was added in the `requirements-dev.txt` and not as a direct dependency

**Comment by inverse** [comment]
@ivandokov #133 was only a partial solution :( I don't know how to resolve `pip` dependencies for the `snap` install. I guess it auto closed this one :(

**Comment by ivandokov** [comment]
I think it will work automatically for snaps as the python plug-in looks for requirements.txt automatically and install the dependencies https://snapcraft.io/docs/python-plugin

**Comment by darkanthey** [comment]
I supposed you need push minor release to snap-store "V1.7.1".

**Comment by blinkeye** [comment]
@ivandokov : I still have the same error with the snap version `v1.7.1`, only downgrading to `1.5.11` resolves the issue.

**Comment by BjornFallman** [comment]
I have similar problem with a install on a fresh ubuntu 22.04 LTS. The tqdm package is installed but still get "ModuleNotFoundError: No module named 'tqdm' " error.
