### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by jlyfshhh** [ivandokov/phockup#137]
$ phockup /Volumes/photo/unorganized /Volumes/Photos/phockup -m -d YYYY/YYYY-MM-DD -o
Traceback (most recent call last):
  File "/opt/homebrew/bin/phockup", line 11, in <module>
    from src.phockup import Phockup
  File "/opt/homebrew/Cellar/phockup/1.7.1/src/phockup.py", line 9, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by tardigradus** [comment]
I get the same error on Ubuntu 20.10 using version 1.7.1 installed via ```snap```.

**Comment by ivandokov** [comment]
@jlyfshhh I guess you are using clone of the repository? You probably pulled the latest version but you also have to run `pip3 install -r requirements.txt`. We have forgot to add this to the install instructions when we added the module.
That's also affecting the packages we deploy.

**Comment by nboisteault** [comment]
I also the same error message with a snap installation in Ubuntu 18.04.

**Comment by garret-linn** [comment]
I installed on macOS via homebrew
and had the same problem

pip3 install tqdm

worked for the install and now phockup works fine

**Comment by ivandokov** [comment]
I resolved the issue [here](https://github.com/ivandokov/phockup/commit/b865b56f31c6fde1eadf71540bcf66ceb7744dd3). A new version will be tagged today.
