### ISSUE TITLE
phockup: error: unrecognized arguments: Output file

### ISSUE THREAD

**Issue by Gruzzen** [ivandokov/phockup#138]
I execute Phockup through an inotify script that watches my input folder, executes a single instance of docker to sort them to the output folder.  This has been running without issue for a while, and I use it to auto sort my auto-backedup pictures from my phone.  However, I noticed recently that at some point thy were no longer  sorted, and tracked down the problem.

I am now getting the following error when running Phockup docker.

phockup: error: unrecognized arguments:  [always the output directory]

My Docker command:

```
 docker run -v /mnt/storage/Server_Photo/_UnSorted:/photobase ivandokov/phockup:latest phockup /photobase/in /photobase/out --date YYYY/M/DD --move
usage: phockup [-h] [-v] [-d DATE] [-m | -l] [-o] [-t] [-y] [--maxdepth 1-255]
               [-r REGEX] [-f DATE_FIELD] [--debug | --quiet | --progress]
               [--log LOG] [--file-type image|video]
               INPUTDIR OUTPUTDIR
phockup: error: unrecognized arguments: /photobase/out
```

**Comment by ivandokov** [comment]
PR #117 removed the need to pass `phockup` argument and you can execute the docker command like this now:
```
docker run -v ~/Pictures:/mnt ivandokov/phockup:latest /mnt/Input /mnt/Output [PHOCKUP ARGUMENTS]
```
