### ISSUE TITLE
NFS mounted directory, path check fails.

### ISSUE THREAD

**Issue by JoeArcher007** [ivandokov/phockup#14]
Hello.

It appears that the application can't seem to work on NFS mounted shares. I've tried to take a look into the code and replicating the issue just running within python itself (the path check) but it works there fine, which is odd.
I've also tried for kicks to change the permissions to the deadly 777. This also didn't seem to affect how it works.
Here are some pictures of what's been tried, and the original command.
![image](https://user-images.githubusercontent.com/20824654/27877442-9d6066fa-6188-11e7-9e2a-a3c2c06baa81.png)
![image](https://user-images.githubusercontent.com/20824654/27877450-aac7ca54-6188-11e7-8e46-dfc37d8d4fc1.png)
![image](https://user-images.githubusercontent.com/20824654/27877460-ba7769aa-6188-11e7-9443-7b8ced8b655b.png)
The mount is as follows:
`server.domain.com:/mnt/JoNas_Vol_1/ on /JoNAS type nfs (rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=ip.ad.dr.ess,mountver=3,mountpor=990,mountproto=udp,locl_locl=none,addr=ip.ad.dre.ss)`

I did also try using . as the initial path, and it seemed to work which was also odd, but I wasn't able to get the secondary path to work.

If you require any more information, let me know.

Thanks!

**Comment by linucksrox** [comment]
I'm having a similar issue, except that the input path is a local ext4 filesystem. It is shared externally over NFS, but I can't even access it locally.
When I try from within the source directory `phockup . /mnt/backup/photos/dst` I get:
```
Output directory "/mnt/backup/photos/dst" does not exist, creating now
Cannot create output directory. No write access!
```
Although my user account is the owner, and this doesn't even work when running sudo.

**Comment by ivandokov** [comment]
I guess you are using the snap version. 
Snap applications are confined to access only the home directory for security reasons. 
If you are storing pictures outside home directory, `/media` or `/run/media` you should use the source code by running the python file directly.
Maybe I should mention this in the documentation.

**Comment by JoeArcher007** [comment]
I guess you could say **oh snap**.

Good to know, and that's totally the case there then. I'll BFS and give it a go.

Thanks again for the tight program!

**Comment by linucksrox** [comment]
I ended up doing a git clone into my home directory, and created a symbolic link to /home/username/phockup/phockup.py in /lib/phockup/ so that I can just git pull whenever I want to update.

**Comment by ivandokov** [comment]
That's also an option, but it depends to git and not everyone wants it

**Comment by linucksrox** [comment]
Oh yea, I could just run python3 /home/username/phockup.py /src /dst
