### ISSUE TITLE
Use it as a library ?

### ISSUE THREAD

**Issue by physispc** [ivandokov/phockup#143]
Hi is it possible to use Phockup as a python library ?

It can be invoked:

1.  phockup.process(**file**) : processes the **file** (rename, move, copy, etc.) and returns a dict {original_path_file : final_path_file}
2. phockup.process(**dir**) : walks the **dir**, process each file, and returns a dict {original_path_file1 : final_path_file1, original_path_file2 : final_path_file2, ... }

Thanks.

**Comment by ivandokov** [comment]
The code is not meant to be used as a library but I am open for implementing changes that will allow the code to be used as a library as long as it doesn't breaks the original meaning of the code.

**Comment by physispc** [comment]
Great! I'm looking forward to have this feature :)
Thanks a lot.

**Comment by ivandokov** [comment]
I think I was misunderstood. I am not going to implement any changes to make the code usable as a library but I am not going to stop any PRs improving this as long as they don't break the current functionality.
You are more than welcome to send a PR.

**Comment by physispc** [comment]
Ok, for now I'm parsing the output in my program.
I'll look into this when I'm done on my side !
