### ISSUE TITLE
Increasing concurrency beyond 1 errors out

### ISSUE THREAD

**Issue by imagesafari** [ivandokov/phockup#149]
If I try to increase concurrency beyond one running a large job, it quits very quickly with an error like this:

 [WARNING] - [Errno 17] File exists: '/mnt/phototest/newrun/2010/12/17'

Seems like multiple threads may be trying to write to the same directory or otherwise stepping on each others toes.

**Comment by unapproachable** [comment]
I just encountered this too.  I'll look at getting a file lock implemented when copying large number of files that target a directory that doesn't exist.   I'll update this issue when I have something.

**Comment by LSgeo** [comment]
I haven't got anything to add to the Manager Lock fork, but if this is a symptom of numerous threads trying to create a directory (that didn't exist, but now does), I think it could be solved using `os.makedirs(fullpath, exist_ok=True)`.

While Locking is a better solution for more general problems with multiprocessing, and I suspect it is better practice and good to implement now, I think short term `exist_ok` might be a simple fix. Depending on how the program works, I don't imagine multiple threads will try to access the same file, where locking becomes more important.

**Comment by unapproachable** [comment]
I was finally able to get a few moments to test out the suggestion from @LSgeo and it appears to sidestep the exceptions that were terminating the multi-threaded run on duplicate folder creation.  It *is* a simple fix to one line, and avoids the introduction of more complexity from the mysteries of the Manager lock.

See [Issue 149 Easy Fix](https://github.com/unapproachable/phockup/tree/feature/issue_149_easy)

PR incoming.

Thank you @LSgeo
