### ISSUE TITLE
Allow to move files instead of copy

### ISSUE THREAD

**Issue by ivandokov** [ivandokov/phockup#15]
Currently the entire process is copying files from one location to another. 
Adding a flag to move files instead of copy will be useful if you are working with big collection of files and the available space is not enough to double the files.

**Comment by j4nw** [comment]
I'd like to take a stab at this.

**Comment by ivandokov** [comment]
@j4nw I admire your quick reaction. I was actually creating this issue for myself (TODO) :)
You are welcome to make a PR if you find something to be improved. I'll be happy to label it with hacktoberfest label.

**Comment by j4nw** [comment]
Oh, I only found it because the label was already there - I happened to open Hacktoberfest issues just as you added it :)

Yeah, I would like to try my hand at tackling this for my first ever OSS pull request.
