### ISSUE TITLE
Option to change output name?

### ISSUE THREAD

**Issue by Chipwingg** [ivandokov/phockup#157]
Is there a way to change the name of the resulting pictures it sorts? Having the names like "20220411-10045155.jpg" can be difficult to read. I prefer dashes, like, "2022-04-11-10045155.jpg" or similar.

Edit: I just saw there is another Issue open about this. I did not mean to double post it. My bad.

**Comment by mixcas** [comment]
Is in the works https://github.com/ivandokov/phockup/issues/65
