### ISSUE TITLE
Add Dockerfile for ARM64

### ISSUE THREAD

**Issue by tiagoqpinto** [ivandokov/phockup#160]
Can we add docker support for ARM64?
I don't think the effort would be huge, I can try to make it myself if I have spare time.

It would help everyone that uses raspberry pi or devices like that to handle/organize media collections.

**Comment by ivandokov** [comment]
Such a PR is more than welcome!

**Comment by tiagoqpinto** [comment]
Actually it's not needed a PR, its just the build and push to DockerHub.
For example this tutorial can help: https://vikaspogu.dev/posts/docker-buildx-setup/

Either way I have created a arm64 image of phockup 1.9.0 tag
https://hub.docker.com/r/tiagoqpinto/phockup

**Comment by ivandokov** [comment]
I added the required steps for the action build process but I get some errors that I don't know what they mean nor how to resolve. @tiagoqpinto do you have any ideas? https://github.com/ivandokov/phockup/actions/runs/3172305517/jobs/5166652121

**Comment by inverse** [comment]
@ivandokov I got this locally too when running buildx locally

https://github.com/docker/buildx/issues/493#issuecomment-957135684

Running this solved it for me.

**Comment by ivandokov** [comment]
I didn't have the errors locally but I'm building it on macOS so I suspect it can be platform specific.
@inverse I don't know how I can run these commands that you referenced inside the Github Action.

**Comment by inverse** [comment]
@ivandokov created a PR that does it by setting up QEMU.
