### ISSUE TITLE
Add automated tests

### ISSUE THREAD

**Issue by ivandokov** [ivandokov/phockup#17]
Currently the code does not have any kind of tests but it should.

I've created a [separate repository](https://github.com/ivandokov/phockup-tests) for these tests because they will have some large dummy files and we do not want to include them in the final software.

**Comment by ladhadha** [comment]
IMHO it's better to implement mocking for testing instead of real files. It will decrease test run time too. What do you think?

**Comment by 3onyc** [comment]
I'm not entirely sure why the dummy files would have to be large, you could use tiny video/image files with the EXIF data required for the tests

**Comment by ladhadha** [comment]
Aggree with @3onyc.

**Comment by 3onyc** [comment]
Anyway, I'm working on this right now

**Comment by ivandokov** [comment]
The RAW files from DSLRs are always large. I saw a way to export a smaller resolution file from Adobe Lightroom, but the file format is not NEF (Nikon) or CR2 (Canon). It is DNG (Adobe).
This was the main reason to assume the dummy files will be large and therefore the tests should be outside the main repository.

**Comment by ivandokov** [comment]
Actually after putting some thought on the topic ... the different file types don't matter, because that is a problem of **exiftool**, not **phockup** as long as it provides the same response.

**Comment by 3onyc** [comment]
Yup, EXIF as a metadata format can be added to any file type, so we don't need to worry about individual formats

**Comment by ivandokov** [comment]
@3onyc can you please check my PR comment.
