### ISSUE TITLE
--max-concurrency not documented in readme

### ISSUE THREAD

**Issue by MildlyInterested** [ivandokov/phockup#184]
As title says it seems like the max-concurrency option is not documented in the readme file.

Is there any reason for this? From my limited testing the option seems to work fine.

Option defined here: https://github.com/ivandokov/phockup/blob/master/phockup.py#L130-L140

**Comment by ivandokov** [comment]
The contributor missed it and I missed noting it too when merging. 
If you want to contribute to the project you can send a PR with the missing documentation.
