### ISSUE TITLE
When used --move delete empty source directories

### ISSUE THREAD

**Issue by ivandokov** [ivandokov/phockup#20]
When the process strategy is changed to **move** (`-m|--move`) the script should check if the source directory for any remaining file and if there are none the directory should be deleted.

This could be done for each subdirectory after each file move process (could be expensive operation) or at the end of the whole process.

**Comment by riyaadazad** [comment]
@ivandokov I personally don't think that removing empty directories should be tied to the move flag, because not all users may want this to be done by default.

**Comment by ivandokov** [comment]
This will happen only when the directory is empty. I don't see how the empty directory is of any use even in your case. You don't know where the photos came from when you are moving them. Please correct me if I'm wrong.

**Comment by rob-miller** [comment]
For the case as @riyaadazad describes: if a directory is called '2018_july_trip_to_spain', seeing the empty directory indicates that the user still needs to go into e.g. Shotwell and tag/annotate some 2018/07 photos as the 'trip to Spain'.  So seems useful to leave as reminder.
