### ISSUE TITLE
File skipped, duplicated file

### ISSUE THREAD

**Issue by salvadorAnt** [ivandokov/phockup#205]
If file is  skipped, due duplicated file, it could be deleted from source

**Comment by ivandokov** [comment]
The software do not delete any source files just in case something failed during the process. That's a security measure against development errors.

**Comment by rob-miller** [comment]
Would you consider a PR for something like a `--movedel` option which would modify the `move` and `skip` behavior to delete the source file if it is detected as a duplicate?  In other words, 

- the user chooses to enable deletions with a long form `--` option, only valid if `move` and `skip` are enabled
- the file has generated a path from EXIF data (so higher risk of filecmp false match for YYYY or YYYY/MM output)
- target_file is present and matches `filecmp.cmp(filename, target_file, shallow=False)`
- only then is source file deleted.

My goal is to process multiple versions of my photo library to get them down to one clean tree.  By deleting the exact duplicates (by criteria above) I'm left with just the files that need EXIF dates added to them.

**Comment by ivandokov** [comment]
I'm not against adding an option to delete source files, but it shouldn't be by default.
