### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by ivandokov** [ivandokov/phockup#21]
It will be awesome to have a progress bar at the bottom of the process. 
With the current way of printing the process data it could be a tricky one.

**Comment by riyaadazad** [comment]
How about adding a completion percentage (sort of like the old apt-get systems on Ubuntu machines) flush right on the last line of the terminal.

Example Terminal:
-----------------------------------------------------------------
|   Unsorted => Sorted                                              |
|   Unsorted => Sorted                                              |
|   Unsorted => Sorted                                              |
|   Unsorted => Sorted                                              |
|   Unsorted => Sorted                                              |
|   Unsorted => Sorted                                              |
|   Unsorted => Sorted                                              |
|   Current File to Work On ...............................9 % |
-----------------------------------------------------------------

**Comment by ivandokov** [comment]
This is exactly what I thought initially. I just lack the time to code it at the moment.
