### ISSUE TITLE
Add option for custom regex for date in filename

### ISSUE THREAD

**Issue by ivandokov** [ivandokov/phockup#22]
There are cases when some cameras do not include the correct EXIF data, but they use filenames with date (and time). There is a guessing code for such filenames (*IMG_20160915_123456.jpg / IMG-20160915-123456.jpg*) but it is for a single more generic filename and any other different filenames are ignored. Adding an option to pass regex for date and time guessing will be good.

**Comment by senden9** [comment]
I can take this bug down.

Should the new flag overrule the EXIF information (if there is any) or should the information from the filename only used if there is no EXIF date in the image?

**Comment by ivandokov** [comment]
The later. Use filename only if the EXIF data does not have the date.
