### ISSUE TITLE
Package for PyPI 

### ISSUE THREAD

**Issue by 3onyc** [ivandokov/phockup#25]
It could be useful to package this for PyPI, for resources on how to do this see the [distutils documentation](https://docs.python.org/3/distutils/index.html)

Maybe a good one for Hacktoberfest @ivandokov?

**Comment by ivandokov** [comment]
Keep in mind that we are on a unknown territory for me so if you suggest that this is required or useful you are welcome to submit a PR.

**Comment by ivandokov** [comment]
Phockup has exiftool dependency which is not a python package. Is it possible to pack it with such a dependency?

**Comment by 3onyc** [comment]
Yeah, it only works for Python dependencies. Could technically depend on one of the Python based EXIF libraries if you wanted to

**Comment by ivandokov** [comment]
I prefer to use the original exiftool. 
I think this is not suitable in the case.
