### ISSUE TITLE
option for preserving original filename

### ISSUE THREAD

**Issue by hurtigerhans** [ivandokov/phockup#34]
It would be nice to have an option
* so that the original filename is preserved
* the original filename is used as pre/postfix for the generated one

**Comment by ivandokov** [comment]
Great suggestions @hurtigerhans! 
Unfortunately I am busy these days and I cannot work on them.
Pull requests are welcome so if you can implement it go for it.

**Comment by YounoYouno** [comment]
This is a great suggestion to be the cherry on top of the cake..
Wish I could be of help to add this feature, maybe in the future hopefully.

**Comment by ivandokov** [comment]
I will be talking a look at this feature in the next days as I think I will have some time.
From a first look I don't think it will be hard to implement but can't be sure until I dig into the code.
Will update the issue once I have progress.

**Comment by ivandokov** [comment]
Done. Released v1.5.6
