### ISSUE TITLE
KeyError: 'MIMEType

### ISSUE THREAD

**Issue by limaunion** [ivandokov/phockup#38]
### Hi, got this error with phockup v1.5.3 while running the following command, don't know what's the issue: 

$ ./phockup.py ~/data.photos/PhotoDVD23 ~/data.photos/PhotoDVD1_new -m -d YYYY.MM

/home/superuser/data.photos/PhotoDVD23/DSC_5469.JPG => /home/superuser/data.photos/PhotoDVD1_new/2011.07/20110709-15204290.jpg
/home/superuser/data.photos/PhotoDVD23/DSC_5470.JPG => /home/superuser/data.photos/PhotoDVD1_new/2011.07/20110709-15210110.jpg
/home/superuser/data.photos/PhotoDVD23/DSC_5471.NDFTraceback (most recent call last):
  File "./phockup.py", line 75, in <module>
    main(sys.argv[1:])
  File "./phockup.py", line 69, in main
    date_regex=date_regex
  File "/home/superuser/data.git/phockup.git/src/phockup.py", line 34, in __init__
    self.walk_directory()
  File "/home/superuser/data.git/phockup.git/src/phockup.py", line 65, in walk_directory
    self.process_file(file)
  File "/home/superuser/data.git/phockup.git/src/phockup.py", line 137, in process_file
    output, target_file_name, target_file_path = self.get_file_name_and_path(file)
  File "/home/superuser/data.git/phockup.git/src/phockup.py", line 176, in get_file_name_and_path
    if exif_data and self.is_image_or_video(exif_data['MIMEType']):
KeyError: 'MIMEType'

**Comment by ivandokov** [comment]
It looks like the file `/home/superuser/data.photos/PhotoDVD23/DSC_5471.NDF` does not provide Mime Type. This is an edge case and phockup should handle it gracefully, but it doesn't. I will provide an update soon.

**Comment by ivandokov** [comment]
The fix is released. Thanks for your bug report!

**Comment by limaunion** [comment]
Yes! just tried and that solved the issue. Thanks!
