### ISSUE TITLE
copies all files

### ISSUE THREAD

**Issue by jmls** [ivandokov/phockup#43]
newbiw question ; when I run , ` phockup ./dropbox ./photos` *all* the files in dropbox are copied 

for example

```
ls -l photos/unknown
-rw-r--r-- 1 root root  944914432 Oct 11 23:49 '2015 h2.zip'
-rw-rw-r-- 1 root root  519722441 Aug  1 17:13 'All Mail'
-rw-rw-r-- 1 root root 1859857537 Jan 14  2018  d-g.zip
-rwxr-xr-x 1 root root        112 Jan 12  2018  flat.sh
-rw-rw-r-- 1 root root  931395873 Jan 15  2018  h-i.zip
-rw-rw-r-- 1 root root      60614 Aug  1 17:10  inbox
-rw-rw-r-- 1 root root     271360 Aug  1 17:21 'Personal Folders.pst'
```
how do I make this program only check / search images and videos ?

**Comment by ivandokov** [comment]
The software is processing all files for safety reasons. 
For example if there is new file type that is still unknown for the exiftool the file will be copied/moved over to unknown directory and this guarantees that you will not lose any files and the source folder is safe to be deleted.

I understand what you are trying to accomplish but there is no way to do it currently. 
Actually the software used to work like this but it was limited by a specified number of file extensions and had the chance to miss some media files which could be actually parsed by the exiftool. 

I suggest you to gather all the source files in a single folder and then run the software on that folder.
