### ISSUE TITLE
Option -o doesn't preserve upercase

### ISSUE THREAD

**Issue by pauloup** [ivandokov/phockup#45]
Using the option --original-filenames, my files still get renamed from "IMG_2018..." to "img_2018..."

To fix it, I had to edit the file **src/phockup.py** and replace the **line 186** from:
```
target_file_name = self.get_file_name(file, date).lower()
```
to:
```
if self.original_filenames:
    target_file_name = self.get_file_name(file, date)
else:
    target_file_name = self.get_file_name(file, date).lower()
```

**Comment by ivandokov** [comment]
Hello @pauloup. Thanks for the report. If you want please submit a PR so you can be a contributor to the project or let me know if you don't want to and I will fix it.

**Comment by pauloup** [comment]
Hi @ivandokov, I'm really new to gifhub, so please may I have your guidance on the best way to make a pull request?

**Comment by ivandokov** [comment]
Here is a good article describing the process https://yangsu.github.io/pull-request-tutorial/ but the sort steps are as follows:
- Fork the repository 
- Make changes to the code and push them to Github. It required to make unit tests for the changes that you've made on the code. I can help you with that if needed once the pull request is created as you can update the pull request code later.
- When you open the page of the forked repository you will see a button to create a Pull Request. Follow the steps.
- Once I have the pull request I will review the code and request changes or merge the code.

**Comment by pauloup** [comment]
Thank you! I believe I was able to fork the repository, commit the changes and make a pull request. I think I'm gonna need help with the unit tests.

**Comment by ivandokov** [comment]
Merged and fixed https://github.com/ivandokov/phockup/pull/47
