### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by pauloup** [ivandokov/phockup#46]
I just started using phockup. I tried to process a folder of 25k images and it took about 1h to complete, with no much processing power being used. So I wondered how better it could be with multi threading support. 

After some coding, I managed to do that. Here are the `time` output with a test folder of 36 images and 4 threads:

Original:
```
~> time phockup test test2 --move 
6.43user 0.52system 0:06.77elapsed 102%CPU (0avgtext+0avgdata 17544maxresident)k
```

Multithread:
```
~> time phockup test test2 --move --threads 4
9.28user 0.69system 0:03.23elapsed 309%CPU (0avgtext+0avgdata 17596maxresident)k
```
 
**Results: Elapsed time from 7s to 3s and CPU usage of 3x**.

I had never played with threads in python before this, so I'm sure my code is not the best way to do it. I'm just making a point that multithread can improve the performance of phockup, since it relies a lot on exiftool, and it ends up being a performance bottle neck.

What I did: In the walk_directory function I split the files list into subsets, and each subset goes into a thread. The --threads (or -x) parameter defines how many threads are going to be used. I also adjusted the print commands to prevent a race condition on stdout. The patches with the code changes I did are attached.

**phockup.py**
[phockup.py-multithread-patch.txt](https://github.com/ivandokov/phockup/files/2685075/phockup.py-multithread-patch.txt)

**src/help.py**
[src-help.py-multithread-patch.txt](https://github.com/ivandokov/phockup/files/2685077/src-help.py-multithread-patch.txt)

**src/phockup.py** 
[src-phockup.py-multithread-patch.txt](https://github.com/ivandokov/phockup/files/2685079/src-phockup.py-multithread-patch.txt)

Thank you for creating and sharing phockup.

**Comment by ivandokov** [comment]
That's a great idea and honestly I really don't know why I haven't thought about this so far. Please make a Pull Request with the proposed changes (I gave you an article about this in #45) and we can test it out and merge the code.

**Comment by ivandokov** [comment]
By the way I am new to Python in general. This is my first and only Python project so far.

**Comment by pauloup** [comment]
Thank you! Maybe I should wait until I have learnt to do the unit tests before pulling a request. And I just liked a lot the way you coded phockup, and I'm learning a lot from it!

**Comment by pauloup** [comment]
In the meantime I looked at other ways to speed up the processing and I found out that exiftool has a huge improvement in speed when using the batch option (by sending many files as the input). 

I had to make some deeper changes to try this, but the result was impressive. The time using batch input for exiftool was just **0.7s** with only 2 threads, compared to the 3.2s of my previous version, and 6.8s of the original code.
```
~> time phockup test test2 --move --threads 2
1.65user 0.11system 0:00.69elapsed 255%CPU (0avgtext+0avgdata 19816maxresident)k
```

I'm waiting for help with the unit tests of my first pull request about preserving filenames uppercase. Then I can learn how to make sure it's everything fine with this multithread code, and make a pull request for it.

**Comment by ivandokov** [comment]
@pauloup thank you for the effort put in the software. It is really appreciated. Unfortunately I am busy these days and it will take awhile to find time and assist you with the unit tests. You can still prepare the pull request and send it. We can write unit tests before merging.

**Comment by unapproachable** [comment]
Can close based on https://github.com/ivandokov/phockup/pull/123
