### ISSUE TITLE
Choose the EXIF date field

### ISSUE THREAD

**Issue by luizcantoni** [ivandokov/phockup#51]
Would be nice to pass an argument in the command-line allowing to choose which EXIF date field should be used as the final image date. In the example below, phockup is using  the CreateDate field, but the year of this field is 2002. For this case DateTimeOriginal is the correct field.

`exiftool -time:all -mimetype -j IMG_20140513_190138258.jpg`

```

[{
  "SourceFile": "IMG_20140513_190138258.jpg",
  "FileModifyDate": "2014:05:13 19:01:38-03:00",
  "FileAccessDate": "2018:12:21 15:02:32-02:00",
  "FileInodeChangeDate": "2018:05:27 20:36:06-03:00",
  "ModifyDate": "2014:05:13 19:01:38",
  "DateTimeOriginal": "2014:05:13 19:01:38",
  "CreateDate": "2002:12:08 12:00:00",
  "MIMEType": "image/jpeg"
}]


```

**Comment by pauloup** [comment]
This seems like a useful option. I remember some old phone I had that recorded really tricky exif dates on its pictures. @ivandokov if you don't mind or are already working on it, could I pull a request to add this one?

**Comment by ivandokov** [comment]
Thank you @luizcantoni for the info. I didn't have a case when these both dated exist and are different so I just used one of them. 
Sure go ahead @pauloup.

**Comment by pauloup** [comment]
@luizcantoni, would you mind if I pull a request to add this feature? Or are you already working on that?

**Comment by luizcantoni** [comment]
@pauloup , go ahead, please. Thank you for that!
