### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by raphaelmonnard** [ivandokov/phockup#56]
I installed the package on a arch config via the `yaourt` command.
I tried to launch the command `phockup` in a bash terminal and got: 

```
ModuleNotFoundError: No module named 'src'
```
It seems that the python module does not exist:
```
ls -al /usr/share/phockup/
total 24
drwxr-xr-x   2 root root  4096 30 déc 11:11 .
drwxr-xr-x 262 root root 12288 30 déc 10:59 ..
-rwxr-xr-x   1 root root  2241 30 déc 11:10 phockup.py
```
How to install correctly the repo on arch?
Thanks for your help !

**Comment by ivandokov** [comment]
Thank you for the report. Unfortunately I have no experience with arch and I definitely did not add the software to arch repositories. The only option that we officially support is using the snap package. Alternatively you can download the source and run it manually as described in the Readme.

**Comment by raphaelmonnard** [comment]
Works well with snap. 

Thanks !
