### ISSUE TITLE
Don't rely on exiftool

### ISSUE THREAD

**Issue by d53dave** [ivandokov/phockup#58]
There are Python libraries that can deal with Exif data, like [ExifRead](https://pypi.org/project/ExifRead/). 

This could be used instead of the manual invocation of exiftool and associated process handling, and would get rid of the external dependency. Win-win.

**Comment by ivandokov** [comment]
Thanks for the suggestion @d53dave. I thought about this initially but the media formats that these other libraries support are really limited. The one that you suggested supports only JPEG and TIFF. The exiftool that we use now is has support for [insane number of file formats](http://owl.phy.queensu.ca/~phil/exiftool/#supported) and this allows the software to organise much wider spectrum of file types.

**Comment by d53dave** [comment]
I haven't taken that into account. Closed.
