### ISSUE TITLE
"Original Filenames" option should leave name fully untouched & should not change filenames to lowercase

### ISSUE THREAD

**Issue by k3vmcd** [ivandokov/phockup#60]
[line 186](https://github.com/ivandokov/phockup/blob/8e7c9aa810d720dd4908102e25129d01509c2814/src/phockup.py#L186) of `src/phockup.py` contains
`target_file_name = self.get_file_name(file, date).lower()`

When using the -o flag to preserve original filenames, the `.lower()` function should not be run on the file.

Filenames should be fully untouched when using the -o flag.

Tested and confirmed that removing the `.lower()` function from this line preserves the original uppercase and lowercase formatting of the filename. However, this should probably only occur when the -o flag is passed, not in all cases as the removal of the `.lower()` function would do.

**Comment by ubershmekel** [comment]
This issue seems resolved when you `git clone` this repo but is not deployed to the brew formula for some reason.

**Comment by ivandokov** [comment]
Indeed I didn't released the new version but now it is done. Apologies for the delay.
