### ISSUE TITLE
Travis test test_exif_reads_files_with_illegal_characters failing only for 3.7

### ISSUE THREAD

**Issue by ivandokov** [ivandokov/phockup#63]
I am not sure why Travis fails at `test_exif_reads_files_with_illegal_characters` [test](https://travis-ci.org/ivandokov/phockup/jobs/527214041#L225) and only for Python 3.7. I'll need some help with this one. Maybe @pauloup can help?

**Comment by stchris** [comment]
The test output says 

```/bin/sh: 1: Syntax error: Unterminated quoted string```

which leads me to believe that the sequence `exif = Exif("input/!#$%&'\"*+-.^_`|~:.jpg")` will be executed by `sh`, because it contains `#!`. I have no explanations for why this would fail on this specific version of Python though.

**Comment by stchris** [comment]
After poking around, the issue seems to be in the way the filename is escape. `re.escape` has this mention in the docs (https://docs.python.org/3/library/re.html?highlight=re%20escape#re.escape):

```Changed in version 3.7: Only characters that can have special meaning in a regular expression are escaped.```

I can try to submit a PR for this.
