### ISSUE TITLE
Recognize JPEGs with .THM extension (from GoPro)

### ISSUE THREAD

**Issue by bzamecnik** [ivandokov/phockup#64]
Some  .THM files (JPEGs) with proper EXIF ended up in `unknown`. `file` command recognized JPEG. Possibly https://github.com/ahupp/python-magic may help.

**Comment by ivandokov** [comment]
Can you please provide a sample thm file so I can take a look and use it for development?

**Comment by bzamecnik** [comment]
Yeah, I can post it when I grab it from a NAS. If you wish I can help with it and make a PR.

**Comment by ivandokov** [comment]
I'd appreciate a PR since I am pretty busy these days. Please make sure to write unit tests for the implementation.

**Comment by bzamecnik** [comment]
![GH010010.THM](https://user-images.githubusercontent.com/446124/58075675-95d50a80-7ba8-11e9-9446-0df97c42b26e.jpg)

Here's the JPEG (md5sum: b882b9781b9846f6c1da6722bfe93b72). GitHub does not allow uploading file with the THM extension. It seems that no conversion was done by GitHub. In all cases (.THM, renamed to .jpg, taking the file downloaded back from GitHub) it moves it to the `unknown/` dir.

Output from exiftool:

```
$ exiftool GH010010.THM 
ExifTool Version Number         : 11.30
File Name                       : GH010010.THM
Directory                       : .
File Size                       : 18 kB
File Modification Date/Time     : 2019:05:15 18:26:10+02:00  # <--- the expected date
File Access Date/Time           : 2019:05:21 09:15:04+02:00
File Inode Change Date/Time     : 2019:05:21 09:09:33+02:00
File Permissions                : rw-r--r--
File Type                       : THM
File Type Extension             : thm
MIME Type                       : image/jpeg
Image Width                     : 160
Image Height                    : 120
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:2 (2 1)
Image Size                      : 160x120
Megapixels                      : 0.019
```

I'll try to investigate what's wrong.

**Comment by bzamecnik** [comment]
Mea culpa. The solution is written in the README. The file doesn't contain EXIF `CreateDate`. The solution is to utilize also `FileModifyDate`:

```
$ phockup tests/input/ tests/output/ -f "CreateDate FileModifyDate" -o
tests/input/GH010010.THM => tests/output/2019/05/15/GH010010.THM
```
