### ISSUE TITLE
write stdout to log file 

### ISSUE THREAD

**Issue by SasikumarN** [ivandokov/phockup#66]
Write STDOUT to log file.

This will be very much useful if any human mistake happened during file copy or move operation.

**Comment by stchris** [comment]
@SasikumarN is it not enough to pipe the output to STDOUT when calling `phockup`?

**Comment by SasikumarN** [comment]
This is an enhancement not required mandatory. 

I felt -l or --log=logfile looks good instead of doing **./phockup SRC DST** | tee logfile

**Comment by ivandokov** [comment]
Since this is not a missing feature or a bug but an enhancement I postpone the implementation unless someone wishes to submit a PR.
