### ISSUE TITLE
readme.md fix for ExifTool.exe link

### ISSUE THREAD

**Issue by robcmo** [ivandokov/phockup#73]
The readme.md document under Installation Windows is the line:

> Download exiftool from the official [website](http://www.sno.phy.queensu.ca/~phil/exiftool/exiftool-10.56.zip) and extract the archive

However, version 10.56 is obsolete (2017-06-06).  The correct link should be https://exiftool.org/ which has current version 11.87 (2020-02-13).  You can validate by going to http://www.sno.phy.queensu.ca/~phil/exiftool/ which redirects to https://exiftool.org/.

[Version History](https://exiftool.org/ancient_history.html)

**Comment by ivandokov** [comment]
It is now linked to the main website and then the user can download the latest version. Thank you!
