### ISSUE TITLE
Sort by filename too

### ISSUE THREAD

**Issue by wmunoz** [ivandokov/phockup#76]
I had a directory with sorted images and I added some others on top of it,  so I ran phockup to get the new ones sorted. In the process of sorting the first ones, the tool moved to unknown instead of looking a the filename or other attributes.

`/home/wilmar/Pictures/sorted/2017/04/20170415-173104.jpg => sorted_images/unknown/20170415-173104.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173242.jpg => sorted_images/unknown/20170415-173242.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173521906057.jpg => sorted_images/2017/04/15/20170415-173521906057.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173525697619.jpg => sorted_images/2017/04/15/20170415-173525697619.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173527947603.jpg => sorted_images/2017/04/15/20170415-173527947603.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173535280797.jpg => sorted_images/2017/04/15/20170415-173535280797.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173538364085.jpg => sorted_images/2017/04/15/20170415-173538364085.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173542739040.jpg => sorted_images/2017/04/15/20170415-173542739040.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173554072463.jpg => sorted_images/2017/04/15/20170415-173554072463.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173556030465.jpg => sorted_images/2017/04/15/20170415-173556030465.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-173849.jpg => sorted_images/unknown/20170415-173849.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-174019666761-2.jpg => sorted_images/2017/04/15/20170415-174019666761.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-174019666761.jpg => sorted_images/2017/04/15/20170415-174019666761-2.jpg
/home/wilmar/Pictures/sorted/2017/04/20170415-203447.mp4 => sorted_images/2017/04/15/20170415-203447.mp4
`

**Comment by ivandokov** [comment]
Maybe you are missing required exif data and you used other options when you sorted the images the first time but not the second?
