### ISSUE TITLE
Classify by year/month only

### ISSUE THREAD

**Issue by ppmt** [ivandokov/phockup#8]
It would be nice if we could choose to only classify the pictures in year/month
For me having all the photos of the same month in one directory is sufficient

**Comment by JoeArcher007** [comment]
I will second @ppmt in this as for myself, I don't take a massive amount of photo's, so trying to narrow down via actual day can be hard enough.

That aside, love the name, and it's direct purpose of organization.

**Comment by ivandokov** [comment]
I'm going to code this feature and combine it with #7

**Comment by limaunion** [comment]
+1 

I'll love to have this option available. Thanks!

**Comment by ivandokov** [comment]
Version 1.3.0 adds this functionality. You can check the documentation here https://github.com/ivandokov/phockup#date-format
