### ISSUE TITLE
HEIC photos taken during daylight savings time are renamed with time offset  in filename, which is invalid on Windows

### ISSUE THREAD

**Issue by trapdoor123** [ivandokov/phockup#83]
I have run Phockup against a library of photos going back a few years, and something odd is happening to the renaming of photos taken since the switch to daylight saving this year. All HEIC photos (and possibly others) are having `+01:00` added to the filename after the formatted date/time string. While fine on ext4, unfortunately `:` is invalid in Windows file names, so when viewed on a Windows machine across the networks, an old 8.3 style filename substitute is displayed instead.

I am not sure why the +01:00 is being appended to this year's photo file names.
Checking back to photos from the last few years, the same issue is _not_ present on photos taken during DST.

Photos from 30-March-2020 as viewed on Linux:
![image](https://user-images.githubusercontent.com/9866255/87358579-0635ac80-c55e-11ea-9897-24ab20476d1c.png)

The same photos view on Windows:
![image](https://user-images.githubusercontent.com/9866255/87358632-1e0d3080-c55e-11ea-9911-804389d5ca6d.png)

An example 2020 file with this issue from this year contains the following suspiciously-similar field names in the EXIF:
`Offset Time                     : +01:00
Offset Time Original            : +01:00`

An example from within the 2019 DST period does _not_ contains these fields in the EXIF, so this may have been something introduced in an iOS update in the intervening period.

Ideally I would _not_ like the offset included in the filename as it makes the filename unreadable in Windows.

**Comment by ivandokov** [comment]
I think this should be fixed by #78. Can you please try latest version and let me know if the issue still persists. 
Thanks.
