### ISSUE TITLE
Date sanity checking

### ISSUE THREAD

**Issue by Avamander** [ivandokov/phockup#84]
It seems that a few platforms add nasty fake EXIF dates to their images, which means they're renamed and sorted to basically random folders. 

Could it be implemented that `phockup` passes/skips images that have dates before the invention of digital cameras or more than a few months in the future?

**Comment by ivandokov** [comment]
I've noticed this too from photos from old phones or weird cameras. Unfortunatelly this is pretty much a guess work. 
I received images with dates in the future which can be detected as invalid date but other than that I think the date sanity checking is pretty much impossible.
