### ISSUE TITLE
this week in pictures

### ISSUE THREAD

**Issue by jaud7of8** [ivandokov/phockup#85]
Would it be possible to have an output option for week, hopefully without the year?  I am trying to reproduce the"this is week in pictures" option that some online photo sharing sites have.

I with phockup, I would pull all the pictures into weekly folders, without the year, then script to have the folder matching this week be chosen to display on magic mirror2 (by copying or linking to the directory that the MMM-ImagesPhotos module uses.)

Thanks

**Comment by jaud7of8** [comment]
I was able to modify the script to separate the pictures in weeks.
This is how the script was modified on Ubuntu 18.04
Install per the instructions

sudo cp /opt/phockup/src/date.py /opt/phockup/src/date.py.bak
sudo nano -c /opt/phockup/src/date.py 

at line 16 insert this
date = date.replace("w", "%V")  # 31 (week)
use the spacebar to align the text, don't use the tab key


at line 90, make the following change change the line

 r'.*[_-](?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})[_-]?(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})')

to 

 r'.*[_-](?P<year>\d{4})(?P<week>\d{2})(?P<month>\d{2})(?P<day>\d{2})[_-]?(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})')


You are inserting (?P<week>\d{2}) into the line of code

To get the photos separated out in weeks with no years, just run phockup with the option 
-d w

**Comment by ivandokov** [comment]
This feature could be implemented with a flag. PRs are welcome!
