### ISSUE TITLE
Add recursivity max depth

### ISSUE THREAD

**Issue by anttitelio** [ivandokov/phockup#92]
It seems that by default the application runs the operations for all the sub-directories, which in many cases might not be what the user needs. Could it be possible to add --maxdepth option which would work like on (GNU) Find?

**Comment by ivandokov** [comment]
Sounds like a good feature. All PRs are more than welcome!

**Comment by anttitelio** [comment]
Unfortunately I don't have the time nor skills to implement the functionality

**Comment by anttitelio** [comment]
That merged issue #104 seems to be completed so this original one must be completed also. Seems to work just like I wanted :+1:
