### ISSUE TITLE
dependency checking for exiftool fails

### ISSUE THREAD

**Issue by FransM** [ivandokov/phockup#93]
I installed phockup with snap, but when I run it nothing happens (no files are moved)
From browsing the source I learned that exiftool is needed. This did not exist on my system.
However the check in dependency.py did not fire and I did not get the error
This is on Ubuntu 2020.4

$ exiftool

Command 'exiftool' not found, but can be installed with:

sudo apt install libimage-exiftool-perl

$ phockup . ../../../../F/
$ phockup . ../../../../F/ -y
Dry run only, not moving files only showing changes
$

**Comment by ivandokov** [comment]
When you are using the snap package it shouldn't ask you to install any additional packages. Unfortunatelly at the moment I don't have Linux to test it. Can someone confirm the issue with the latest snap build?

**Comment by FransM** [comment]
Actually after I installed with snap and I installed exiftool with the command given above things still did not work for me.
No files were processed.
I continued by fetching latest.tar.gz and installing that.
That one works like a charm.

One suggestion that I think is not present yet, is to create a log file with files that could not be processed (e.g. because they already exist). For now I just redirected to a LOG file so I can grep for "duplicate"

**Comment by ivandokov** [comment]
Snaps are self contained packages with no external dependencies. I am not expecting to make it work by installing an outside dependency as the snap is not using outside tools. 

Your suggestion is duplicate or #66 but I do not have the time to work on it now so PRs are more than welcome!

**Comment by ivandokov** [comment]
@FransM please try with the latest version of the snap package and let me know if the issue is still there.
