### ISSUE TITLE
Custom EXIF not found ? 

### ISSUE THREAD

**Issue by Yfksw65** [ivandokov/phockup#98]
Hello,

i have a new bug.

I try to run :

`phockup --date="YYYY/MM" --date-field="DateTimeOriginal" inputdir outputdir`

But all of file is going in unknown dir

when i made a `exiftool -time:all -mimetype -j examplepic.jpg`

i have :

```
[{
  "SourceFile": "examplepic.jpg",
  "FileModifyDate": "2020:04:16 02:07:51+00:00",
  "FileAccessDate": "2021:02:01 19:12:38+00:00",
  "FileInodeChangeDate": "2020:04:16 02:07:51+00:00",
  "ModifyDate": "2019:12:30 20:21:36",
  "DateTimeOriginal": "2019:12:30 20:21:36",
  "MIMEType": "image/jpeg"
}]
```

Do you have an idea ? 

thank you

**Comment by ivandokov** [comment]
Unfortunatelly the migration to the new way of parsing arguments in #87 introduced some bugs of this kind and since we only have unit tests but no integration ones we have some of these bugs slipping in. It is fixed now in 1.5.26
